<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Loregrove.Application\Loregrove.Application.csproj" />
    <ProjectReference Include="..\Loregrove.Infrastructure.Sqlite\Loregrove.Infrastructure.Sqlite.csproj" />
  </ItemGroup>
</Project>
