<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Loregrove.Application\Loregrove.Application.csproj" />
  </ItemGroup>

</Project>
