// <auto-generated />
using System;
using Loregrove.Infrastructure.Sqlite.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Loregrove.Infrastructure.Sqlite.Persistence.Migrations
{
    [DbContext(typeof(LoregroveDbContext))]
    [Migration("20260813081457_ProvenancePreservingChunksAndFts5")]
    partial class ProvenancePreservingChunksAndFts5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Loregrove.Domain.Sources.Chunk", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("CharacterLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChunkKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChunkSetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentVersionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ParsedArtifactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChunkKey")
                        .IsUnique();

                    b.HasIndex("ChunkSetId", "Ordinal")
                        .IsUnique();

                    b.HasIndex("ParsedArtifactId", "DocumentVersionId");

                    b.HasIndex("ChunkSetId", "ParsedArtifactId", "DocumentVersionId");

                    b.ToTable("Chunks", (string)null);
                });

            modelBuilder.Entity("Loregrove.Domain.Sources.ChunkEvidenceSpan", b =>
                {
                    b.Property<Guid>("ChunkId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnchorEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnchorStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChunkEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChunkStart")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DocumentVersionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParsedArtifactId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceAnchorId")
                        .HasColumnType("TEXT");

                    b.HasKey("ChunkId", "Ordinal");

                    b.HasIndex("ChunkId", "ParsedArtifactId", "DocumentVersionId");

                    b.HasIndex("SourceAnchorId", "ParsedArtifactId", "DocumentVersionId");

                    b.ToTable("ChunkEvidenceSpans", null, t =>
                        {
                            t.HasCheckConstraint("CK_ChunkEvidenceSpans_Anchor", "AnchorStart >= 0 AND AnchorEnd > AnchorStart");

                            t.HasCheckConstraint("CK_ChunkEvidenceSpans_Chunk", "ChunkStart >= 0 AND ChunkEnd > ChunkStart");
                        });
                });

            modelBuilder.Entity("Loregrove.Domain.Sources.ChunkSet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChunkSchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChunkerFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChunkerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChunkerVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentVersionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ParsedArtifactId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentVersionId")
                        .IsUnique()
                        .HasDatabaseName("IX_ChunkSets_CurrentDocumentVersionId")
                        .HasFilter("IsCurrent = 1");

                    b.HasIndex("ParsedArtifactId", "ChunkerFingerprint")
                        .IsUnique();

                    b.HasIndex("ParsedArtifactId", "DocumentVersionId");

                    b.ToTable("ChunkSets", (string)null);
                });

            modelBuilder.Entity("Loregrove.Domain.Sources.LexicalSearchEntry", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChunkId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SourceDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RowId");

                    b.HasIndex("ChunkId")
                        .IsUnique()
                        .HasFilter("ChunkId IS NOT NULL");

                    b.HasIndex("DocumentVersionId");

                    b.HasIndex("SourceDocumentId");

                    b.HasIndex("DocumentVersionId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("IX_LexicalSearchEntries_SourceVersion")
                        .HasFilter("Kind = 0");

                    b.ToTable("LexicalSearchEntries", (string)null);
                });

            modelBuilder.Entity("Loregrove.Domain.Sources.ParsedArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactObjectKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("BlockCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Completeness")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigurationFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentVersionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParserFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParserVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SafeDiagnosticCode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("WarningCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DocumentVersionId")
                        .IsUnique()
                        .HasDatabaseName("IX_ParsedArtifacts_CurrentDocumentVersionId")
                        .HasFilter("IsCurrent = 1");

                    b.HasIndex("DocumentVersionId", "ParserFingerprint")
                        .IsUnique();

                    b.ToTable("ParsedArtifacts", (string)null);
                });

            modelBuilder.Entity("Loregrove.Domain.Sources.ProcessingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentVersionId")
                        .IsUnique();

                    b.HasIndex("State");

                    b.ToTable("ProcessingJobs", (string)null);
                });

            modelBuilder.Entity("Loregrove.Domain.Sources.SourceAnchor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentVersionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocatorJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LocatorKind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocatorSchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedTextHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ParsedArtifactId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentVersionId");

                    b.HasIndex("ParsedArtifactId");

                    b.HasIndex("ParsedArtifactId", "DocumentVersionId");

                    b.HasIndex("ParsedArtifactId", "Ordinal")
                        .IsUnique();

                    b.ToTable("SourceAnchors", (string)null);
                });

            modelBuilder.Entity("Loregrove.Domain.Sources.SourceDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CurrentVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceKind")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SourceDocuments", (string)null);
                });

            modelBuilder.Entity("Loregrove.Domain.Sources.SourceDocumentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(67)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PreviousVersionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessingState")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.HasIndex("DocumentId");

                    b.HasIndex("PreviousVersionId");

                    b.ToTable("SourceDocumentVersions", (string)null);
                });

            modelBuilder.Entity("Loregrove.Domain.Sources.Chunk", b =>
                {
                    b.HasOne("Loregrove.Domain.Sources.ChunkSet", null)
                        .WithMany()
                        .HasForeignKey("ChunkSetId", "ParsedArtifactId", "DocumentVersionId")
                        .HasPrincipalKey("Id", "ParsedArtifactId", "DocumentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Loregrove.Domain.Sources.ChunkEvidenceSpan", b =>
                {
                    b.HasOne("Loregrove.Domain.Sources.Chunk", null)
                        .WithMany()
                        .HasForeignKey("ChunkId", "ParsedArtifactId", "DocumentVersionId")
                        .HasPrincipalKey("Id", "ParsedArtifactId", "DocumentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Loregrove.Domain.Sources.SourceAnchor", null)
                        .WithMany()
                        .HasForeignKey("SourceAnchorId", "ParsedArtifactId", "DocumentVersionId")
                        .HasPrincipalKey("Id", "ParsedArtifactId", "DocumentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Loregrove.Domain.Sources.ChunkSet", b =>
                {
                    b.HasOne("Loregrove.Domain.Sources.ParsedArtifact", null)
                        .WithMany()
                        .HasForeignKey("ParsedArtifactId", "DocumentVersionId")
                        .HasPrincipalKey("Id", "DocumentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Loregrove.Domain.Sources.LexicalSearchEntry", b =>
                {
                    b.HasOne("Loregrove.Domain.Sources.Chunk", null)
                        .WithMany()
                        .HasForeignKey("ChunkId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Loregrove.Domain.Sources.SourceDocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("DocumentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Loregrove.Domain.Sources.SourceDocument", null)
                        .WithMany()
                        .HasForeignKey("SourceDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Loregrove.Domain.Sources.ParsedArtifact", b =>
                {
                    b.HasOne("Loregrove.Domain.Sources.SourceDocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("DocumentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Loregrove.Domain.Sources.ProcessingJob", b =>
                {
                    b.HasOne("Loregrove.Domain.Sources.SourceDocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("DocumentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Loregrove.Domain.Sources.SourceAnchor", b =>
                {
                    b.HasOne("Loregrove.Domain.Sources.SourceDocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("DocumentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Loregrove.Domain.Sources.ParsedArtifact", null)
                        .WithMany()
                        .HasForeignKey("ParsedArtifactId", "DocumentVersionId")
                        .HasPrincipalKey("Id", "DocumentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Loregrove.Domain.Sources.SourceDocumentVersion", b =>
                {
                    b.HasOne("Loregrove.Domain.Sources.SourceDocument", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Loregrove.Domain.Sources.SourceDocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("PreviousVersionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
