// <auto-generated />
using System;
using Loregrove.Infrastructure.Sqlite.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Loregrove.Infrastructure.Sqlite.Persistence.Migrations
{
    [DbContext(typeof(LoregroveDbContext))]
    partial class LoregroveDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Loregrove.Domain.Sources.ParsedArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactObjectKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("BlockCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigurationFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Completeness")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentVersionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParserFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParserVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SafeDiagnosticCode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("WarningCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DocumentVersionId")
                        .IsUnique()
                        .HasDatabaseName("IX_ParsedArtifacts_CurrentDocumentVersionId")
                        .HasFilter("IsCurrent = 1");

                    b.HasIndex("DocumentVersionId", "ParserFingerprint")
                        .IsUnique();

                    b.ToTable("ParsedArtifacts", (string)null);
                });

            modelBuilder.Entity("Loregrove.Domain.Sources.ProcessingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentVersionId")
                        .IsUnique();

                    b.HasIndex("State");

                    b.ToTable("ProcessingJobs", (string)null);
                });

            modelBuilder.Entity("Loregrove.Domain.Sources.SourceAnchor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentVersionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocatorJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LocatorKind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocatorSchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedTextHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ParsedArtifactId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentVersionId");

                    b.HasIndex("ParsedArtifactId");

                    b.HasIndex("ParsedArtifactId", "DocumentVersionId");

                    b.HasIndex("ParsedArtifactId", "Ordinal")
                        .IsUnique();

                    b.ToTable("SourceAnchors", (string)null);
                });

            modelBuilder.Entity("Loregrove.Domain.Sources.SourceDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CurrentVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceKind")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SourceDocuments", (string)null);
                });

            modelBuilder.Entity("Loregrove.Domain.Sources.SourceDocumentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(67)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PreviousVersionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessingState")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.HasIndex("DocumentId");

                    b.HasIndex("PreviousVersionId");

                    b.ToTable("SourceDocumentVersions", (string)null);
                });

            modelBuilder.Entity("Loregrove.Domain.Sources.ParsedArtifact", b =>
                {
                    b.HasOne("Loregrove.Domain.Sources.SourceDocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("DocumentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Loregrove.Domain.Sources.ProcessingJob", b =>
                {
                    b.HasOne("Loregrove.Domain.Sources.SourceDocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("DocumentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Loregrove.Domain.Sources.SourceAnchor", b =>
                {
                    b.HasOne("Loregrove.Domain.Sources.SourceDocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("DocumentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Loregrove.Domain.Sources.ParsedArtifact", null)
                        .WithMany()
                        .HasForeignKey("ParsedArtifactId", "DocumentVersionId")
                        .HasPrincipalKey("Id", "DocumentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Loregrove.Domain.Sources.SourceDocumentVersion", b =>
                {
                    b.HasOne("Loregrove.Domain.Sources.SourceDocument", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Loregrove.Domain.Sources.SourceDocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("PreviousVersionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
